// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4UCXsZUTyYlA5CAhIDYTw1QCtXGVWOuo',
    appId: '1:828309903998:web:a30bf7c972678fb760562f',
    messagingSenderId: '828309903998',
    projectId: 'amst-g5-lab5-flutter',
    authDomain: 'amst-g5-lab5-flutter.firebaseapp.com',
    databaseURL: 'https://amst-g5-lab5-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'amst-g5-lab5-flutter.appspot.com',
    measurementId: 'G-FEE7VF9NJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo0Ay0-wTZ70olWT0NwsUTjUYeRkEOJrw',
    appId: '1:828309903998:android:d10b11b94225da6460562f',
    messagingSenderId: '828309903998',
    projectId: 'amst-g5-lab5-flutter',
    databaseURL: 'https://amst-g5-lab5-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'amst-g5-lab5-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK3FbqIesmRrJXpA1O_vVDNqlruxmbq4E',
    appId: '1:828309903998:ios:4187c376b18cb3ba60562f',
    messagingSenderId: '828309903998',
    projectId: 'amst-g5-lab5-flutter',
    databaseURL: 'https://amst-g5-lab5-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'amst-g5-lab5-flutter.appspot.com',
    iosClientId: '828309903998-55ucttiatrd1ltq1nm2qu38o0onma7do.apps.googleusercontent.com',
    iosBundleId: 'com.example.amstG5Lab5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK3FbqIesmRrJXpA1O_vVDNqlruxmbq4E',
    appId: '1:828309903998:ios:a4fdce2e9280887960562f',
    messagingSenderId: '828309903998',
    projectId: 'amst-g5-lab5-flutter',
    databaseURL: 'https://amst-g5-lab5-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'amst-g5-lab5-flutter.appspot.com',
    iosClientId: '828309903998-kgv98kbsqjpip614p8ac2tn8geemivar.apps.googleusercontent.com',
    iosBundleId: 'com.example.amstG5Lab5.RunnerTests',
  );
}
